// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"RelativeTouchPad","status":true,"description":"相対タッチパッドプラグイン","parameters":{"タッチ有効領域":"0,0,816,624","パッド画像ファイル":"","アロー画像ファイル":"","パッド画像不透明度":"255"}}
];
